#!/bin/bash

# kill all daemons, format the HDFS and restart the daemons

echo "============================================================" >&2
echo "(1) kill all daemons, format the HDFS and restart the daemons" >&2
echo "============================================================" >&2
echo "exec: killall -9 java" >&2
echo "------------------------------------------------------------" >&2
killall -9 java

echo "------------------------------------------------------------" >&2
echo "exec: ~/init-hdfs" >&2
echo "------------------------------------------------------------" >&2
~/init-hdfs

echo "------------------------------------------------------------" >&2
echo "exec: ~/start-hadoop" >&2
echo "------------------------------------------------------------" >&2
~/start-hadoop

